name: Next.js CI

# NOTE: Split workflow - Next.js CI runs automatically, Contracts CI runs manually only
#
# WORKFLOW STRUCTURE:
# 1. nextjs-ci job: Runs automatically on Next.js changes, never touches contracts
# 2. compile-contracts job: Runs ONLY when manually triggered with [contracts] in commit message
#
# This completely prevents automatic snforge test execution while allowing manual contract compilation
#
# MANUAL EXECUTION FOR CONTRACTS:
# - Go to Actions tab in GitHub
# - Select "Next.js CI" workflow
# - Click "Run workflow" button
# - In the commit message field, add [contracts] to trigger contract compilation
# - Example: "fix: update contract [contracts]"
#
# IMPORTANT: No automatic snforge test execution occurs in this workflow
# Contract compilation only runs when [contracts] is in the commit message

on:
  push:
    paths:
      - "packages/nextjs/**"
  pull_request:
    branches:
      - main
    paths:
      - "packages/nextjs/**"
  workflow_dispatch:  # Allow manual execution

jobs:
  # Main Next.js CI job - ONLY for Next.js changes
  nextjs-ci:
    runs-on: ${{ matrix.os }}
    # Only runs for Next.js changes - NO contracts, NO snforge
    if: github.event_name == 'push' || github.event_name == 'pull_request'

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [lts/*]

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Setup node env
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: "yarn"
          #cache-dependency-path: packages/nextjs/yarn.lock

      - name: Install dependencies (Next.js)
        run: yarn install --immutable
        working-directory: ./packages/nextjs

      - name: Install scarb
        uses: software-mansion/setup-scarb@v1
        with:
          tool-versions: ./packages/snfoundry/contracts/.tool-versions
          scarb-lock: ./packages/snfoundry/contracts/Scarb.lock

      # Note: This job ONLY handles Next.js - no snforge, no contract compilation
      # Contract compilation is in separate compile-contracts job

      - name: Run Next.js lint
        run: yarn next:lint --max-warnings=0
        working-directory: ./packages/nextjs

      - name: Check typings on Next.js
        run: yarn next:check-types
        working-directory: ./packages/nextjs

      - name: Run Next.js tests
        run: yarn test run
        working-directory: ./packages/nextjs

      - name: Build Next.js project
        run: yarn build
        working-directory: ./packages/nextjs

  # Cairo contract compilation job - runs ONLY when manually triggered for contracts
  # This job only compiles contracts, never executes tests
  compile-contracts:
    runs-on: ubuntu-latest
    # Only run when manually triggered AND specifically for contracts
    if: github.event_name == 'workflow_dispatch' && contains(github.event.head_commit.message, '[contracts]')

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Install scarb
        uses: software-mansion/setup-scarb@v1
        with:
          tool-versions: ./packages/snfoundry/contracts/.tool-versions
          scarb-lock: ./packages/snfoundry/contracts/Scarb.lock

      # Build Cairo contracts - ONLY compilation, no snforge, no tests
      - name: Build Cairo Contracts
        run: |
          echo "🔨 Compiling Cairo contracts..."
          cd packages/snfoundry/contracts
          scarb clean
          scarb build
          echo "✅ Cairo contracts compiled successfully"
