name: Next.js CI

on:
  push:
    paths:
      - "packages/nextjs/**"
      - ".github/workflows/**"
  pull_request:
    branches:
      - main
    paths:
      - "packages/nextjs/**"
      - ".github/workflows/**"
  workflow_dispatch: {}

jobs:
  nextjs-ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [lts/*]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: yarn
          cache-dependency-path: packages/nextjs/yarn.lock

      - name: Install dependencies
        run: yarn install --immutable
        working-directory: ./packages/nextjs

      - name: Lint
        run: yarn lint --max-warnings=0
        working-directory: ./packages/nextjs

      - name: Type check
        run: yarn check-types
        working-directory: ./packages/nextjs

      - name: Run tests
        run: yarn test --run
        working-directory: ./packages/nextjs

      - name: Build
        run: yarn build
        working-directory: ./packages/nextjs
