name: Next.js CI

on:
  push:
    paths:
      - "packages/snfoundry/contracts/**"
      - "packages/nextjs/**"
  pull_request:
    branches:
      - main
    paths:
      - "packages/nextjs/**"
      - "packages/snfoundry/contracts/**"

jobs:
  ci:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [lts/*]

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Setup node env
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: "yarn"
          #cache-dependency-path: packages/nextjs/yarn.lock

      - name: Install dependencies (Next.js)
        run: yarn install --immutable
        working-directory: ./packages/nextjs

      - name: Install scarb
        uses: software-mansion/setup-scarb@v1
        with:
          tool-versions: ./packages/snfoundry/contracts/.tool-versions
          scarb-lock: ./packages/snfoundry/contracts/Scarb.lock

      # Install snfoundry manually to avoid automatic test execution
      - name: Install snfoundry
        run: |
          curl -L https://github.com/foundry-rs/starknet-foundry/releases/download/v0.48.0/snforge-v0.48.0-linux-amd64.tar.gz | tar -xz
          sudo mv snforge-v0.48.0-linux-amd64/snforge /usr/local/bin/snforge
          sudo chmod +x /usr/local/bin/snforge

      - name: Clean and Build Contracts
        run: |
          cd packages/snfoundry/contracts
          scarb clean
          scarb build

      # TODO: Uncomment when tests are implemented
      # - name: Run smart contract tests
      #   run: yarn test

      # TODO: Uncomment when snfoundry formatting is needed
      # - name: Check Code Format
      #   run: yarn format:check

      - name: Run Next.js lint
        run: yarn next:lint --max-warnings=0
        working-directory: ./packages/nextjs

      - name: Check typings on Next.js
        run: yarn next:check-types
        working-directory: ./packages/nextjs

      - name: Run Next.js tests
        run: yarn test run
        working-directory: ./packages/nextjs

      - name: Build Next.js project
        run: yarn build
        working-directory: ./packages/nextjs
